# Generated by Django 4.0.2 on 2022-02-13 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalPublications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paper_title', models.CharField(max_length=70)),
                ('Year', models.DateField()),
                ('Co_Author', models.CharField(max_length=30)),
                ('Volume', models.IntegerField()),
                ('Publisher', models.CharField(max_length=50)),
                ('Indexing', models.IntegerField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_api.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='ConfrencePublications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paper_title', models.CharField(max_length=70)),
                ('Year', models.DateField()),
                ('Co_Author', models.CharField(max_length=30)),
                ('Volume', models.IntegerField()),
                ('Publisher', models.CharField(max_length=50)),
                ('Indexing', models.IntegerField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_api.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='BookPublications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paper_title', models.CharField(max_length=70)),
                ('Year', models.DateField()),
                ('Co_Author', models.CharField(max_length=30)),
                ('Volume', models.IntegerField()),
                ('Publisher', models.CharField(max_length=50)),
                ('Indexing', models.IntegerField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_api.faculty')),
            ],
        ),
    ]
