# Generated by Django 4.0.2 on 2022-02-13 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_api', '0002_journalpublications_confrencepublications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_title', models.CharField(max_length=70)),
                ('Year', models.DateField()),
                ('Co_Author', models.CharField(blank=True, max_length=30, null=True)),
                ('Edition', models.IntegerField()),
                ('Publisher', models.CharField(max_length=50)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_api.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='ConfrencePublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organizer', models.CharField(max_length=70)),
                ('Year', models.DateField()),
                ('Co_Author', models.CharField(blank=True, max_length=30, null=True)),
                ('Proceeding', models.IntegerField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_api.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='JournalPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paper_title', models.CharField(max_length=70)),
                ('Year', models.DateField()),
                ('Co_Author', models.CharField(blank=True, max_length=30, null=True)),
                ('Volume', models.IntegerField()),
                ('Publisher', models.CharField(max_length=50)),
                ('Indexing', models.IntegerField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_api.faculty')),
            ],
        ),
        migrations.RemoveField(
            model_name='confrencepublications',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='journalpublications',
            name='faculty',
        ),
        migrations.DeleteModel(
            name='BookPublications',
        ),
        migrations.DeleteModel(
            name='ConfrencePublications',
        ),
        migrations.DeleteModel(
            name='JournalPublications',
        ),
    ]
