# Generated by Django 4.0.2 on 2022-03-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_api', '0004_alter_bookpublication_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='Email',
            field=models.EmailField(default='null', max_length=254),
        ),
    ]
